# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(720, 808)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 9, 0, 1, 1)
        self.spin_size = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.spin_size.setObjectName("spin_size")
        self.gridLayout_2.addWidget(self.spin_size, 11, 1, 1, 1)
        self.button_directory = QtWidgets.QPushButton(self.centralwidget)
        self.button_directory.setObjectName("button_directory")
        self.gridLayout_2.addWidget(self.button_directory, 1, 1, 1, 2)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 11, 2, 1, 1)
        self.radio_eleves_auto = QtWidgets.QRadioButton(self.centralwidget)
        self.radio_eleves_auto.setObjectName("radio_eleves_auto")
        self.eleves_group = QtWidgets.QButtonGroup(MainWindow)
        self.eleves_group.setObjectName("eleves_group")
        self.eleves_group.addButton(self.radio_eleves_auto)
        self.gridLayout_2.addWidget(self.radio_eleves_auto, 6, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 10, 0, 1, 1)
        self.radio_eleves_man = QtWidgets.QRadioButton(self.centralwidget)
        self.radio_eleves_man.setObjectName("radio_eleves_man")
        self.eleves_group.addButton(self.radio_eleves_man)
        self.gridLayout_2.addWidget(self.radio_eleves_man, 6, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 6, 0, 1, 1)
        self.button_go = QtWidgets.QPushButton(self.centralwidget)
        self.button_go.setObjectName("button_go")
        self.gridLayout_2.addWidget(self.button_go, 0, 0, 1, 3)
        self.text_eleves = QtWidgets.QTextEdit(self.centralwidget)
        self.text_eleves.setObjectName("text_eleves")
        self.gridLayout_2.addWidget(self.text_eleves, 7, 0, 1, 1)
        self.radio_side_no = QtWidgets.QRadioButton(self.centralwidget)
        self.radio_side_no.setObjectName("radio_side_no")
        self.side_group = QtWidgets.QButtonGroup(MainWindow)
        self.side_group.setObjectName("side_group")
        self.side_group.addButton(self.radio_side_no)
        self.gridLayout_2.addWidget(self.radio_side_no, 10, 2, 1, 1)
        self.text_comp = QtWidgets.QTextEdit(self.centralwidget)
        self.text_comp.setObjectName("text_comp")
        self.gridLayout_2.addWidget(self.text_comp, 4, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 11, 0, 1, 1)
        self.radio_comp_auto = QtWidgets.QRadioButton(self.centralwidget)
        self.radio_comp_auto.setObjectName("radio_comp_auto")
        self.comp_group = QtWidgets.QButtonGroup(MainWindow)
        self.comp_group.setObjectName("comp_group")
        self.comp_group.addButton(self.radio_comp_auto)
        self.gridLayout_2.addWidget(self.radio_comp_auto, 3, 1, 1, 1)
        self.radio_solutions_yes = QtWidgets.QRadioButton(self.centralwidget)
        self.radio_solutions_yes.setObjectName("radio_solutions_yes")
        self.solutions_group = QtWidgets.QButtonGroup(MainWindow)
        self.solutions_group.setObjectName("solutions_group")
        self.solutions_group.addButton(self.radio_solutions_yes)
        self.gridLayout_2.addWidget(self.radio_solutions_yes, 9, 1, 1, 1)
        self.label_directory = QtWidgets.QLabel(self.centralwidget)
        self.label_directory.setObjectName("label_directory")
        self.gridLayout_2.addWidget(self.label_directory, 1, 0, 1, 1)
        self.radio_comp_man = QtWidgets.QRadioButton(self.centralwidget)
        self.radio_comp_man.setObjectName("radio_comp_man")
        self.comp_group.addButton(self.radio_comp_man)
        self.gridLayout_2.addWidget(self.radio_comp_man, 3, 2, 1, 1)
        self.line_directory = QtWidgets.QLineEdit(self.centralwidget)
        self.line_directory.setObjectName("line_directory")
        self.gridLayout_2.addWidget(self.line_directory, 2, 0, 1, 3)
        self.radio_side_yes = QtWidgets.QRadioButton(self.centralwidget)
        self.radio_side_yes.setObjectName("radio_side_yes")
        self.side_group.addButton(self.radio_side_yes)
        self.gridLayout_2.addWidget(self.radio_side_yes, 10, 1, 1, 1)
        self.radio_solutions_no = QtWidgets.QRadioButton(self.centralwidget)
        self.radio_solutions_no.setObjectName("radio_solutions_no")
        self.solutions_group.addButton(self.radio_solutions_no)
        self.gridLayout_2.addWidget(self.radio_solutions_no, 9, 2, 1, 1)
        self.radio_note_yes = QtWidgets.QRadioButton(self.centralwidget)
        self.radio_note_yes.setObjectName("radio_note_yes")
        self.note_grop = QtWidgets.QButtonGroup(MainWindow)
        self.note_grop.setObjectName("note_grop")
        self.note_grop.addButton(self.radio_note_yes)
        self.gridLayout_2.addWidget(self.radio_note_yes, 8, 1, 1, 1)
        self.radio_note_no = QtWidgets.QRadioButton(self.centralwidget)
        self.radio_note_no.setObjectName("radio_note_no")
        self.note_grop.addButton(self.radio_note_no)
        self.gridLayout_2.addWidget(self.radio_note_no, 8, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 8, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 720, 22))
        self.menubar.setObjectName("menubar")
        self.menuFichier = QtWidgets.QMenu(self.menubar)
        self.menuFichier.setObjectName("menuFichier")
        self.menuAide = QtWidgets.QMenu(self.menubar)
        self.menuAide.setObjectName("menuAide")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuitter = QtWidgets.QAction(MainWindow)
        self.actionQuitter.setObjectName("actionQuitter")
        self.action_propos = QtWidgets.QAction(MainWindow)
        self.action_propos.setObjectName("action_propos")
        self.menuFichier.addAction(self.actionQuitter)
        self.menuAide.addAction(self.action_propos)
        self.menubar.addAction(self.menuFichier.menuAction())
        self.menubar.addAction(self.menuAide.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Solutions"))
        self.button_directory.setText(_translate("MainWindow", "Parcourir…"))
        self.label_7.setText(_translate("MainWindow", "cm"))
        self.radio_eleves_auto.setText(_translate("MainWindow", "Automatique"))
        self.label_5.setText(_translate("MainWindow", "Exercices côte à côte"))
        self.radio_eleves_man.setText(_translate("MainWindow", "Manuel"))
        self.label.setText(_translate("MainWindow", "comp.csv"))
        self.label_2.setText(_translate("MainWindow", "eleves.csv"))
        self.button_go.setText(_translate("MainWindow", "Fais de la magie…"))
        self.radio_side_no.setText(_translate("MainWindow", "Non"))
        self.label_6.setText(_translate("MainWindow", "Taille exercice (horizontale)"))
        self.radio_comp_auto.setText(_translate("MainWindow", "Automatique"))
        self.radio_solutions_yes.setText(_translate("MainWindow", "Oui"))
        self.label_directory.setText(_translate("MainWindow", "Répertoire principal"))
        self.radio_comp_man.setText(_translate("MainWindow", "Manuel"))
        self.radio_side_yes.setText(_translate("MainWindow", "Oui"))
        self.radio_solutions_no.setText(_translate("MainWindow", "Non"))
        self.radio_note_yes.setText(_translate("MainWindow", "Oui"))
        self.radio_note_no.setText(_translate("MainWindow", "Non"))
        self.label_4.setText(_translate("MainWindow", "Notes"))
        self.menuFichier.setTitle(_translate("MainWindow", "Fichier"))
        self.menuAide.setTitle(_translate("MainWindow", "Aide"))
        self.actionQuitter.setText(_translate("MainWindow", "Quitter"))
        self.action_propos.setText(_translate("MainWindow", "À propos"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

